version: '3'

services:

  defuse-backend:
    build: ./backend
    container_name: defuse-backend
    ports:
      - 5000:5000
    expose:
      - 5000
    environment:
        - FLASK_HOST=0.0.0.0
        - FLASK_PORT=5000
    entrypoint: python3
    command: app.py
    volumes:
      - ./backend:/app

  defuse-ui:
    build: ./defuse
    container_name: defuse-ui
    ports:
      - 4200:4200
    expose:
      - 4200
    volumes:
      - /app/node_modules
      - ./defuse:/app
