version: '3'

services:

  defuse-backend:
    build: ./defuse-backend
    container_name: defuse-backend
    ports:
      - 5000:5000
    expose:
      - 5000
    environment:
        - FLASK_HOST=0.0.0.0
        - FLASK_PORT=5000
    entrypoint: python3
    command: app.py
    volumes:
      - ./defuse-backend:/app

  defuse-frontend:
    build: ./defuse-frontend
    container_name: defuse-frontend
    ports:
      - 4200:4200
    expose:
      - 4200
    volumes:
      - /app/node_modules
# For development only:       - ./defuse-frontend:/app
