# Generated by Django 3.1.2 on 2020-10-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('owner', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('default_branch', models.CharField(blank=True, default='master', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('num_issues', models.IntegerField(blank=True, default=0)),
                ('num_releases', models.IntegerField(blank=True, default=0)),
                ('num_stars', models.IntegerField(blank=True, default=0)),
                ('num_watchers', models.IntegerField(blank=True, default=0)),
                ('primary_language', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.CharField(blank=True, default='', max_length=30)),
                ('pushed_at', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
    ]
