# Generated by Django 3.0.5 on 2021-02-02 14:07

import apis.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixingcommit',
            name='labels',
            field=djongo.models.fields.ArrayField(blank=True, model_container=apis.models.Label),
        ),
    ]
