# Generated by Django 3.1.3 on 2020-11-05 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureProneFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filepath', models.CharField(editable=False, max_length=300)),
                ('commit', models.CharField(editable=False, max_length=50)),
                ('fixing_commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.fixingcommit')),
            ],
        ),
    ]
