# Generated by Django 3.1.3 on 2020-11-04 17:18

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('running', 'running'), ('completed', 'completed'), ('error', 'error')], default='pending', editable=False, max_length=10)),
                ('name', models.CharField(choices=[('none', 'none'), ('mine-fixing-commits', 'mine-fixing-commits'), ('mine-fixed-files', 'mine-fixed-files'), ('mine-failure-prone-files', 'mine-failure-prone-files'), ('extract-metrics', 'extract-metrics'), ('train', 'train')], default='none', max_length=50)),
                ('data', apis.models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
