# Generated by Django 3.1.2 on 2020-10-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixingcommit',
            name='false_positive',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
