# Generated by Django 3.1.3 on 2020-11-07 14:28

import apis.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='comments_ratio',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='commit_frequency',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='core_contributors',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='has_ci',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='has_license',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='iac_ratio',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='issue_frequency',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='sloc',
        ),
        migrations.AddField(
            model_name='repository',
            name='indicators',
            field=apis.models.JSONField(blank=True, null=True),
        ),
    ]
