# Generated by Django 3.1.3 on 2020-11-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repository',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apis.repositories'),
            preserve_default=False,
        ),
    ]
