# Generated by Django 3.0.5 on 2021-02-02 14:08

import apis.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20210202_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixingcommit',
            name='labels',
            field=djongo.models.fields.ArrayField(default=[{'label': 'FAILURE-PRONE'}], model_container=apis.models.Label),
        ),
    ]
