# Generated by Django 3.1.3 on 2020-11-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_metricsfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectpredictionmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Metrics',
        ),
    ]
