# Generated by Django 3.1.2 on 2020-10-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_fixingcommit_false_positive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixingcommit',
            old_name='false_positive',
            new_name='is_false_positive',
        ),
    ]
