# Generated by Django 3.1.3 on 2020-11-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_task_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='data',
        ),
    ]
