# Generated by Django 3.1.3 on 2020-11-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20201106_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefectPredictionModel',
            new_name='PredictiveModel',
        ),
    ]
