# Generated by Django 3.1.3 on 2020-11-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_remove_task_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='state',
        ),
    ]
