# Generated by Django 3.1.3 on 2020-11-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20201106_1224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictiveModel',
        ),
    ]
